language: python

python:
  - "3.6"

install:
  - pip install flake8 pytest

script:
  - flake8 .
  - python setup.py sdist
  - python -mpip install dist/*.tar.gz
  - pytest tests

deploy:
  - provider: pypi
    user: __token__
    # password: $PYPI_PASSWORD
    distributions: sdist bdist_wheel
    on:
      tags: true
